### ISSUE TITLE
Scrolling behind preloader

### ISSUE THREAD

**Issue by leecrossley** [framework7io/framework7#192]
It's possible to scroll content behind the modal preloader.

It could be prevented with something like this (iOS only):

``` css
.ios .modal-overlay-visible {
    overflow: scroll;
    -webkit-overflow-scrolling: touch;
}
```

I'm not sure if modal-overlay-visible is the correct class (I've not tested it and I'm not sure where else it might be used). This would add scrolling to the overlay itself (although it doesn't need it, so nothing would scroll) and prevent scrolling of the items.
