### ISSUE TITLE
[navbar][vue]navbar hidden property has no effect on iOS

### ISSUE THREAD

**Issue by tiptronic** [framework7io/framework7#2229]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Framework7 Version: 2.0.10
* Platform and Target: iOS

If I add a hidden property to my navbar, it has no effect on iOS. On md it works.
``` html
<f7-page>
     <f7-navbar hidden>
       ...
    </f7-navbar>
</f7-page>
```

You can also see the effect, if you add that property to the official kitchen-sink

--

I add this second one here, because it's likely related:

If I remove the navbar from the page, it is gone, but if I navigate 'Back' from a page which has a navbar, the navbar is not there, but there's still 44px padding at the top of page-content.

If I add:
``` css
.ios .navbar-hidden ~ *:not(.no-navbar) .page-content, .ios .navbar-hidden ~ .page-content {
	padding-top: 0px;
}
```
it works
