### ISSUE TITLE
phonegap google maps with framework7 v2

### ISSUE THREAD

**Issue by innoflash** [framework7io/framework7#2289]
Hi Framework7 developers.

i am having a serious problem working with [phonegap google maps](https://github.com/mapsplugin/cordova-plugin-googlemaps) with Framework7 esp v2,

I am required to select a div in my HTML to place a map here is what i did:

HTML Code:
```HTML
    <div class="page-content">
        <div id="map_canvas">
            the map canvas
        </div>
    </div>
```

CSS Code:
```css
#map_canvas, #journey_canvas, #routeMaps, #settingsmap{
    width: 100%;
    height: 100%;
    background-color: #0f0f0f;
    position: fixed;
   /* z-index: 5500;*/
}
```
JavaScript:
```javascript
var div = document.getElementById("map_canvas");
        map = plugin.google.maps.Map.getMap(div, {
            controls: {
                myLocationButton: true
            },
            gestures: {
                'scroll': true,
                'tilt': true,
                'rotate': true,
                'zoom': true
            }
        });
```
There is more logic to the JS file but on my android device when i open this page i am getting the page overlapping the map.

**THE MAP IS RENDERED BUT IS NOT REPLACING THE ORIGINAL HTML**
![ygn4b 1](https://user-images.githubusercontent.com/12772919/37656529-f2dfca9c-2c50-11e8-9e12-b1f24ce6f6d5.jpg)

**And here how it looked in F7 v1** 
![bdsye 1](https://user-images.githubusercontent.com/12772919/37656555-0a8048ac-2c51-11e8-9722-77c0cc452287.jpg)
