### ISSUE TITLE
Toggle component make the separators of list items blink

### ISSUE THREAD

**Issue by popo1221** [framework7io/framework7#2376]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Framework7 Version: 2.2.5
* Platform and Target: IOS, ANDROID, PC.
* Live Link or JSFiddle: http://framework7.io/docs-demos/toggle.html

### What you did
Click the toggle

### Expected Behavior
The separators of list items won't blink.

### Actual Behavior
The separators of list items blink.

**Comment by popo1221** [comment]
Additionally, when I add codes according to https://stackoverflow.com/questions/6332485/transformscale-causing-blinking-when-hovering?answertab=votes#tab-top
```css
.list.simple-list li,
.ios .simple-list li:after,
 {
  -webkit-backface-visibility: hidden; 
   backface-visibility: hidden;
}
```
It seems can fix the issue.
Is there a better way to fix it?
