### ISSUE TITLE
[v3] Bug on page scrolling area (with fix)

### ISSUE THREAD

**Issue by JCKodel** [framework7io/framework7#2426]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Framework7 Version: v3 beta 6
* Platform and Target: Any
* Live Link or JSFiddle: Sorry, nobody ain't got time for that (https://www.youtube.com/watch?v=zGxwbhkDjZM)

### What you did
Build a list with group-title items and scroll.

### Expected Behavior
The scrollbar should not be clipped (hidden behind the navbar/statusbar). The sticky labels shoud work.

### Actual Behavior
Two problems solved at the same time:

1) The scrollbar is behind the navbar (it is ugly and kinda non functional for certain users with certain mouse pads):
![image](https://user-images.githubusercontent.com/379339/41177474-a32c807a-6b3a-11e8-86e2-c3a3aff62be6.png)

2) Using mobile scroll, the stick labels are also hidden behind navbar:
On mobile:
![image](https://user-images.githubusercontent.com/379339/41177504-be32a336-6b3a-11e8-88ea-adad1d6e6f83.png)

On tablet/desktop:
![image](https://user-images.githubusercontent.com/379339/41177520-d1832cd0-6b3a-11e8-8da2-e457f5f87708.png)

It seems that stick labels aren't working on mobile, but the truth is that is hidden beneath navbar.

Both issues have the same fix:

```css
@media (min-width: 768px)
{
	.md .navbar ~ * .page-content, .md .navbar ~ .page-content
	{
		border-top: solid transparent 64px;
		padding-top: 0;
	}
}

.md .navbar ~ * .page-content, .md .navbar ~ .page-content
{
	border-top: solid transparent 56px;
	padding-top: 0;
}

.ios .navbar ~ *:not(.no-navbar) .page-content, .ios .navbar ~ .page-content
{
	border-top: solid transparent 44px;
	padding-top: 0;
}
```

By using a border instead of padding, I'm displacing the chrome of the element X pixels, and not just their contents. It has the same behavior, but now both scroll and stick labels are fixed.

Guess need the same kind of fix for subnavbar, toolbar, tabbar, etc.
