### ISSUE TITLE
Set Dialog width

### ISSUE THREAD

**Issue by owen-mills** [framework7io/framework7#2601]
**Is your feature request related to a problem? Please describe.**
On any display larger than a small phone, the alert dialog and other dialogs seem extremely narrow, especially with a large amount of text.

**Describe the solution you'd like**
There should be a property to set the dialog width in the settings, and the css would be adjusting accordingly. This cannot be fixed with just a CSS rule because the margin-left seems to be dependent on the width and the display size.

**Comment by nolimits4web** [comment]
Use `cssClass: 'my-dialog'` parameter for dialog, and just specify in your CSS:
```css
.ios .my-dialog, .md .my-dialog {
  width: 400px;
  margin-left: -200px;
}
```
