### ISSUE TITLE
Back button is visible on big screens on detail page in master-detail view.

### ISSUE THREAD

**Issue by akralj** [framework7io/framework7#3041]
* Framework7 version: 4.0.6
* Platform and Target: Desktop Chrome, Safari. it works correct on ios12 (ipad simulator)
* Live Link or JSFiddle: framework7 kitchensink

### Describe the bug
The back button should not be visible, but it is. Same is true for framework7-vue

### To Reproduce
1. Start the kitchensink by going to: http://localhost:3000/kitchen-sink/core/
2. Click on Master-Detail (Split View)
3. Click on Detail Page 1 in a browser window, which width is > 800 px (master-detail-breakpoint)

### Expected behavior
The Back button should not be visible

### Actual Behavior
The Back button is visible

### Screenshots
<img width="1278" alt="screen shot 2019-02-27 at 11 25 21" src="https://user-images.githubusercontent.com/147344/53483778-88652400-3a82-11e9-867a-b8dfd257f285.png">

### Additional context
I guess, there is a css rule missing.

**Comment by nolimits4web** [comment]
Just add custom CSS rule to hide it. There are a lot of cases when it should be there and there could be different layouts:

```css
.view-master-detail .navbar-master-detail .link.back,
.view-master-detail .page-master-detail .navbar .link.back {
    display: none;
}
```
