### ISSUE TITLE
swipeback is slow  when current page has toolbar(subnavbar,messagebar)

### ISSUE THREAD

**Issue by boboxiaodd** [framework7io/framework7#3196]
framework7 version: the 4.4.0
cordova + ios12.2

### To Reproduce
1. page1 push to page2
2. page2 has toolbar bottom
3. swipeback to page1
4. swipeback is slow ,  `toolbar messagebar` is slow more
(the same issues when the page has `Subnavbar`)

but i use custom toolbar , is fast when swipeback:
```css
    .bottom-bar{
        display: flex;
        justify-content: space-between;
        position: fixed;
        bottom: 0;
        left: 0;
        width: 100vw;
        background-color: var(--f7-bars-bg-color);
        height: calc(var(--f7-toolbar-height) + var(--f7-safe-area-bottom) + 7px);
        z-index: 100;
    }
```
