### ISSUE TITLE
Feature Request: Dislodge page behind sheet modal

### ISSUE THREAD

**Issue by willmero** [framework7io/framework7#3225]
Feature request: Similar to how many iOS applications dislodge the main page and move it backwards in the z direction, it would be awesome to allow the sheet modal to move the page behind in a similar way. Example would be in the apple podcasts app:
https://youtu.be/bFNEOLrxc-8

Note at the top of the screen, as the modal opens, the page moves backwards in unison.

This would be awesome, but unsure how difficult it would be to accomplish.

**Comment by nolimits4web** [comment]
Do you mean something we have at https://jobs.framework7.io/ ? Visit from phone or enable mobile mode in browser and click "How to post job ad?" on home page:

<img width="321" alt="1" src="https://user-images.githubusercontent.com/999588/60185796-3adfa480-9833-11e9-9808-17fec482a517.png">

It is just done with few custom styles:

```less
@media (max-width: 629px), (max-height: 629px) {
  .framework7-root:not(.framework7-initializing) {
    background: #000;
  }
  .view-main {
    transition-duration: 400ms;
    transition-property: transform, border-radius;
    transform-origin: center bottom;
    border-radius: 0;
  }
  .popup {
    overflow: hidden;
    border-radius: 15px 15px 0 0;
    top: calc(var(--f7-statusbar-height) + var(--f7-navbar-height));
    height: calc(100% - var(--f7-statusbar-height) - var(--f7-navbar-height));
  }
  .with-modal-popup .view-main {
    transform: scale(0.95);
    border-radius: 15px;
  }
}
```
