### ISSUE TITLE
Custom Icons Not Display on ``md`` Theme 

### ISSUE THREAD

**Issue by KiddoV** [framework7io/framework7#4241]
### Describe the bug

I use ``Fontawesome`` as custom icons on the tab bar.

With the ``ios`` theme, everything works as expected:
![ios](https://github.com/framework7io/framework7/assets/28552977/1cb06031-66cf-47dc-89dd-ad4e04e56ee1)

However, with the ``md`` theme, the icons disappear:
![md](https://github.com/framework7io/framework7/assets/28552977/31ec8e0a-0697-41fc-ba73-33d074199d52)

I notice it is because on ``md`` theme, we have this CSS:
```css
.md .tabbar i.icon::before, .md .tabbar-icons i.icon::before {
    content: '';
    width: 64px;
    height: 32px;
    border-radius: 32px;
    position: absolute;
    left: 50%;
    top: 50%;
    transform: translateX(-50%) translateY(-50%) scaleX(0.5);
    background: var(--f7-tabbar-link-active-icon-bg-color);
    opacity: 0;
    transition-duration: 200ms;
    z-index: -1;
}
```
That ``CSS`` is the rounded pills that highlight active tab. The ``content: '';`` would override my custom icon class for ``Fontawesome``:
```css
.fa-circle-dollar-to-slot:before, .fa-donate:before {
    content: "\f4b9";
}
``` 

Is there anyway to get around with this?
Can we change the ``rounded`` pill to use ``::after`` instead of ``::before`` so it would not conflict with ``Fontawesome`` CSS?

Thanks,
